module HarchWeb.Markup.Attributes
  ( Attribute,
    DataAttributeSuffix,
    ElementId,
    SafeUrl,
    ariaDescribedBy,
    ariaErrorMessage,
    ariaInvalid,
    ariaLabel,
    ariaLive,
    autocomplete,
    className,
    dataAttribute,
    dataAttributeSuffixText,
    dataFlag,
    elementId,
    elementIdText,
    enctype,
    formAction,
    fragmentHref,
    hidden,
    href,
    inputMode,
    inputType,
    lang,
    labelFor,
    literalElementId,
    maxLength,
    method,
    minLength,
    mkDataAttributeSuffix,
    mkElementId,
    mkSafeUrl,
    name,
    required,
    requiredSafeUrlOrDie,
    role,
    safeUrlText,
    tabIndex,
    value,
  )
where

import HarchWeb.Markup.Implementation
