module HarchWeb.Markup.Attributes
  ( Attribute,
    ElementId,
    ariaLabel,
    ariaLive,
    autocomplete,
    className,
    dataAttribute,
    dataFlag,
    elementId,
    enctype,
    formAction,
    hidden,
    href,
    inputMode,
    inputType,
    labelFor,
    literalElementId,
    maxLength,
    method,
    minLength,
    mkElementId,
    name,
    required,
    role,
    value,
  )
where

import HarchWeb.Markup.Implementation
