module HarchWeb.Markup.Elements
  ( Html,
    MarkupContent (toHtml),
    Tag,
    TrustedHtml,
    anchorTag,
    buttonTag,
    codeTag,
    divTag,
    element,
    formTag,
    fragment,
    headingOneTag,
    headingTwoTag,
    inputTag,
    labelTag,
    listItemTag,
    listTag,
    optionTag,
    paragraphTag,
    renderHtml,
    sectionTag,
    selectTag,
    text,
    trustedHtml,
    voidElement,
  )
where

import HarchWeb.Markup.Implementation
