-- | Public ACME and certificate-automation API.
--
-- The implementation is deliberately split into private modules so callers can
-- depend on this stable boundary rather than ACME protocol, OpenSSL, certbot,
-- or challenge-store internals.  The lower-level helpers below remain exported
-- temporarily for compatibility with the umbrella 'HarchWeb' API; new
-- applications should generally start with 'AcmeConfig', 'AcmeChallengeStore',
-- and the workflow functions.
module HarchWeb.Acme
  ( AcmeAuthorizationResponse (..),
    AcmeChallengeResponse (..),
    AcmeChallengeStore (..),
    AcmeConfig (..),
    AcmeDirectoryResponse (..),
    AcmeJwk (..),
    AcmeOrderIdentifier (..),
    AcmeOrderResponse (..),
    AcmeRequestAuth (..),
    ActiveAcmeChallenge (..),
    CertbotConfig (..),
    JsonValue (..),
    PreparedAcmeChallenge (..),
    RuntimeAcmeBindPlan (..),
    acmeCertificateRequestConfig,
    acmeChallengeResponseForRequest,
    acmeHttp01ChallengeToken,
    acmeJwkThumbprintBytes,
    base64urlText,
    buildAcmeJwsBody,
    buildAcmeKeyAuthorization,
    certbotCertificateName,
    certbotHasOption,
    certbotOptionValues,
    createAcmeAccount,
    createAcmeOrder,
    decodeAcmeJsonResponse,
    escapeJsonCharacter,
    fetchAcmeCertificate,
    fetchAcmeDirectory,
    fetchAcmeNonce,
    finalizeAcmeOrder,
    firstCertbotDomain,
    generateAcmeAccountKey,
    generateAcmeCertificateRequest,
    hexTextToByteString,
    jsonArrayBytes,
    jsonArrayItems,
    jsonBoolBytes,
    jsonObjectEntryParser,
    jsonObjectBytes,
    jsonObjectFields,
    jsonOptionalTextArrayField,
    jsonOptionalTextField,
    jsonRequiredField,
    jsonRequiredTextField,
    jsonStringCharacterParser,
    jsonStringBytes,
    jsonTextField,
    jsonValueParser,
    loadAcmeJwk,
    mailtoAcmeContact,
    matchesRuntimeAcmeChallenge,
    openSslSha256,
    parseAcmeAuthorizationResponse,
    parseAcmeChallengeResponse,
    parseAcmeDirectoryResponse,
    parseAcmeOrderIdentifier,
    parseAcmeOrderResponse,
    parseJsonValue,
    performAcmeJwsRequest,
    performAcmeRequest,
    pollAcmeOrder,
    pollAcmeOrderWithRetries,
    prepareAcmeAuthorization,
    prepareCertbotManualTlsBindPlan,
    registerAcmeChallenges,
    renderAcmeResponseBody,
    responseHeaderText,
    runOpenSslCommand,
    runOpenSslTextCommand,
    runtimeCertbotArguments,
    signOpenSslRs256,
    splitCertbotDomainValue,
    triggerAcmeChallenge,
    unicodeJsonCharacterParser,
    unregisterAcmeChallenges,
    validAcmeHttp01ChallengeToken,
  )
where

import HarchWeb.Acme.Certbot.Options
  ( certbotHasOption,
    certbotOptionValues,
    firstCertbotDomain,
    splitCertbotDomainValue,
  )
import HarchWeb.Acme.Certbot.Runtime
  ( RuntimeAcmeBindPlan (..),
    certbotCertificateName,
    prepareCertbotManualTlsBindPlan,
    runtimeCertbotArguments,
  )
import HarchWeb.Acme.Challenge
  ( AcmeChallengeStore (..),
    ActiveAcmeChallenge (..),
    acmeChallengeResponseForRequest,
    acmeHttp01ChallengeToken,
    matchesRuntimeAcmeChallenge,
    registerAcmeChallenges,
    unregisterAcmeChallenges,
    validAcmeHttp01ChallengeToken,
  )
import HarchWeb.Acme.Crypto (acmeJwkThumbprintBytes, base64urlText, hexTextToByteString)
import HarchWeb.Acme.Json
  ( JsonValue (..),
    escapeJsonCharacter,
    jsonArrayBytes,
    jsonArrayItems,
    jsonBoolBytes,
    jsonObjectBytes,
    jsonObjectEntryParser,
    jsonObjectFields,
    jsonOptionalTextArrayField,
    jsonOptionalTextField,
    jsonRequiredField,
    jsonRequiredTextField,
    jsonStringBytes,
    jsonStringCharacterParser,
    jsonTextField,
    jsonValueParser,
    parseJsonValue,
    unicodeJsonCharacterParser,
  )
import HarchWeb.Acme.KeyMaterial
  ( acmeCertificateRequestConfig,
    generateAcmeAccountKey,
    generateAcmeCertificateRequest,
    loadAcmeJwk,
  )
import HarchWeb.Acme.OpenSsl (openSslSha256, runOpenSslCommand, runOpenSslTextCommand, signOpenSslRs256)
import HarchWeb.Acme.Protocol.Client
  ( buildAcmeJwsBody,
    buildAcmeKeyAuthorization,
    decodeAcmeJsonResponse,
    fetchAcmeNonce,
    performAcmeJwsRequest,
    performAcmeRequest,
    renderAcmeResponseBody,
    responseHeaderText,
  )
import HarchWeb.Acme.Protocol.Decode
  ( parseAcmeAuthorizationResponse,
    parseAcmeChallengeResponse,
    parseAcmeDirectoryResponse,
    parseAcmeOrderIdentifier,
    parseAcmeOrderResponse,
  )
import HarchWeb.Acme.Protocol.Types
  ( AcmeAuthorizationResponse (..),
    AcmeChallengeResponse (..),
    AcmeDirectoryResponse (..),
    AcmeJwk (..),
    AcmeOrderIdentifier (..),
    AcmeOrderResponse (..),
    AcmeRequestAuth (..),
    PreparedAcmeChallenge (..),
  )
import HarchWeb.Acme.Protocol.Workflow
  ( createAcmeAccount,
    createAcmeOrder,
    fetchAcmeCertificate,
    fetchAcmeDirectory,
    finalizeAcmeOrder,
    mailtoAcmeContact,
    pollAcmeOrder,
    pollAcmeOrderWithRetries,
    prepareAcmeAuthorization,
    triggerAcmeChallenge,
  )
import HarchWeb.Server.Config (AcmeConfig (..), CertbotConfig (..))
