-- | Stable public CSRF facade. Page/action lifecycle and signed-token backend
-- ownership are private sibling modules, preserving one 'CsrfProtection'.
module HarchWeb.Csrf
  ( CsrfBinding,
    CsrfBindingDigest,
    CsrfBindingResolution (..),
    CsrfCookieDisposition (..),
    CsrfCookieMaxAgeSeconds,
    CsrfKeyId,
    CsrfIssuance (..),
    CsrfPagePreparationFailure (..),
    CsrfProtection (..),
    CsrfSigningKey,
    CsrfToken,
    CsrfVerification (..),
    SignedCsrfKeyring,
    SignedCsrfPolicy,
    PageCsrf,
    PageSecurity,
    csrfBindingFromCanonicalBytes,
    csrfBindingDigest,
    csrfBindingDigestText,
    csrfClearCookieHeader,
    csrfCookieMaxAgeSeconds,
    mkCsrfCookieMaxAgeSeconds,
    csrfTokenText,
    defaultCsrfCookieMaxAgeSeconds,
    defaultSignedCsrfPolicy,
    generateCsrfSigningKey,
    generateCsrfToken,
    mkCsrfKeyId,
    mkCsrfToken,
    mkSignedCsrfPolicy,
    mkCsrfSigningKey,
    mkSignedCsrfKeyring,
    mkPageCsrf,
    mkPageSecurity,
    pageCsrfBinding,
    pageCsrfCookieDisposition,
    pageCsrfCookieMaxAge,
    pageCsrfValue,
    pageSecurityCsrf,
    pageSecurityRuntimeNonce,
    samePageSecurity,
    preparePageSecurity,
    csrfProtectionUnavailable,
    SignedCsrfDependencies (..),
    signedCsrfProtection,
    validateCsrfToken,
  )
where

import HarchWeb.Csrf.Lifecycle
import HarchWeb.Csrf.Signed (SignedCsrfDependencies (..), signedCsrfProtection)
